# Build settings
# markdown: kramdown

# http://jekyllrb.com/docs/github-pages/#project-page-url-structure


title: Harry Reyes Nieva
description: |
  I'm a postdoctoral research scientist at Columbia University in the City of New York. 
  My research leverages artificial intelligence to advance health equity science, 
  improve the quality and safety of patient care, and support knowledge discovery in medicine.
baseurl: http://www.harryreyesnieva.com
url: "http://www.harryreyesnieva.com" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  harryreyesnieva
twitter_username: harryreyesnieva
linkedin_username: harryreyes

header_pages:
  - about.md
  - cv.md
  - projects.md
  - publications.md
  - presentations.md
  - teaching.md
  - news.md
theme: minima
# Build settings
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-twitter-plugin